name: CI Checks (Develop Branch PRs)

on:
  pull_request:
    branches:
      - develop
      - main
  push:
    branches:
      - develop
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Ensure this matches your package.json engine
          cache: 'yarn' # Cache node_modules for faster builds

      - name: Install Dependencies
        run: yarn install --frozen-lockfile # Use --frozen-lockfile for CI consistency

      - name: Turborepo Cache (Optional but Recommended)
        uses: actions/cache@v4
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-

          
      - name: Formart
        run: yarn format # This will run 'turbo run lint' which you configured earlier
      # - name: Type Check All Affected Code
      #   run: yarn typecheck # This will run 'turbo run typecheck'

      - name: Run All Tests
        run: yarn test # This will run 'turbo run test'

      # --- Optional Security Scan (Highly Recommended) ---
      - name: Run NPM Audit for Vulnerabilities
        run: yarn audit --level critical || true # Fail only on critical, or remove || true to fail on any

      # - name: Lint All Affected Code
      #   run: yarn lint # This will run 'turbo run lint' which you configured earlier